### ISSUE TITLE
An error occurred while extracting *.LSB. Engine version: Version: 107 (LiveMaker2).

### ISSUE THREAD

**Issue by TXT2GAM** [pmrowla/pylivemaker#117]
* pylivemaker version: 23.3
* Python version: 3.11.3
* Operating System: Windows 11
* LiveMaker game: 未亡人～ぬめり合う肉欲と淫らに濡れる蜜壺

### Description

I want to extract the text content of this game, but encountered an error. 
I suspect it's due to different engine versions.
```
lmlsb probe END3.lsb
END3.lsb
LiveMaker compiled LSB script file:
  Version: 107 (LiveMaker2)
  Total commands: 2500
    Command types: If, Else, Label, Jump, Call, Wait, Flip, Calc, ObjDel, TextIns
  Total text scenarios: 1417
    Unlabeled scenario
      LiveNovel scenario version: 100
      TpWd types: TWdChar
      Approx. character count: 12
      Approx. line count: 0
    Unlabeled scenario
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Scripts\lmlsb.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\livemaker\cli\lmlsb.py", line 91, in probe
    tpwd_types.add(wd.type)
                   ^^^^^^^
AttributeError: 'int' object has no attribute 'type'
```
The error message is as follows.

### What I Did

```
lmlsb extractcsv --encoding=cp932 END3.lsb END3.csv
Extracting END3.lsb ...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Scripts\lmlsb.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\livemaker\cli\lmlsb.py", line 1169, in extractcsv
    for id_, block in lsb.get_text_blocks():
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\livemaker\lsb\lmscript.py", line 534, in get_text_blocks
    for i, block in enumerate(scenario.get_text_blocks()):
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\livemaker\lsb\novel.py", line 935, in get_text_blocks
    return LNSText.from_tpword(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\livemaker\lsb\novel.py", line 1737, in from_tpword
    if w.type == TWdType.TWdChar:
       ^^^^^^
AttributeError: 'int' object has no attribute 'type'
```

**Comment by TXT2GAM** [comment]
.lsb File(Use Garbro to unpack): [https://drive.google.com/file/d/1zOACpo5xXie-M851Doo7d_4DBAAqG5mK/view?usp=share_link](url)

**Comment by pmrowla** [comment]
pylm 1.1.1 was just released which should fix this issue

**Comment by TXT2GAM** [comment]
`Successfully installed construct-2.10.68 pylivemaker-1.1.1`
`lmlsb extractcsv --encoding=cp932 END3.lsb END3.csv
Extracting END3.lsb ...
Extracted 304 text blocks.`
There were no error messages, but there are still some issues. The majority of the extracted content is meaningless symbols.
I suspect it's because the text in different engine versions exists in different forms.
![image](https://github.com/pmrowla/pylivemaker/assets/134926662/466c1c57-1163-4cf1-ac37-3038d7d19e34)
The .lsb file has been provided in the previous reply. Please refer to it if needed.

**Comment by pmrowla** [comment]
The problem is that the text scripts use tags that aren't supported in the CSV extraction/insertion method. If you use `lmlsb dump END3.lsb > END3.lsb.txt` to get the raw text dump or `lmlsb extract END3.lsb` to see the actual .lns scripts, you can see the text content for your game:

```
<TXSPN>【<VAR NAME="UserName" unk3="None">】「久し振りに<VAR NAME="UserName2" unk3="None">に抱いて貰えるぞ。どうだ嬉しいだろう？」
```

The problem here is specifically that the scripts for your game use `<VAR>` tags that are never closed (either with corresponding `</VAR>` or with `<VAR ... />` syntax). Since the tags are never closed, the CSV only sees the leading `<TXSPN>【` (which becomes the single `【` in the CSV)

This may be the default behavior for LNS script version 100, but I don't have any other sample games to test against since that version of the engine is so old.

---

If you are just looking to get the text content for your game I would suggest just using the raw content via `lmlsb dump` or `lmlsb extract` instead of using `extractcsv`.

If you are looking to actually do a translation patch, I'm not sure that pylm will work properly for your game even if you use the raw LNS scripts. Basically I have only ever tested the pylm LNS compiler (which is needed to reinsert patched/translated scripts) for engine versions that use LNS script version 102 and later.

**Comment by TXT2GAM** [comment]
Thank you very much for your help!
Just having the text is enough, I don't want to create a release version of the translation patch. A comparison table of Japanese and Chinese translations is sufficient.
