### ISSUE TITLE
error extracting lsb file

### ISSUE THREAD

**Issue by gggssepgf** [pmrowla/pylivemaker#121]
* pylivemaker version:1.1.1
* Python version:3.10.8
* Operating System:win11 x64
* LiveMaker game:トライアド・リリーティア

### Description

error extracting lsb file

### What I Did

I extracted game using：
lmar x game.ext -o game_files
then I try to extract one lsb file using：
lmlsb extractcsv --encoding=utf-8-sig 00001643.lsb 00001643.csv
and here's error log：
E:\Lilytear_v1.3>lmlsb extractcsv --encoding=utf-8-sig 00001643.lsb 00001643.csv
Extracting 00001643.lsb ...
Traceback (most recent call last):
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\Scripts\lmlsb.exe\__main__.py", line 7, in <module>
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\livemaker\cli\lmlsb.py", line 1167, in extractcsv
    for id_, block in lsb.get_text_blocks():
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\livemaker\lsb\lmscript.py", line 530, in get_text_blocks
    for i, block in enumerate(scenario.get_text_blocks()):
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\livemaker\lsb\novel.py", line 926, in get_text_blocks
    return LNSText.from_tpword(self)
  File "C:\Users\15869\AppData\Local\Programs\Python\Python310\lib\site-packages\livemaker\lsb\novel.py", line 1728, in from_tpword
    if w.type == TWdType.TWdChar:
AttributeError: 'int' object has no attribute 'type'

by the way,there's no error if I use pylm 1.0.4

**Comment by pmrowla** [comment]
Regression after the fix for #117

**Comment by pmrowla** [comment]
This is fixed in v1.1.2 which was just released
