### ISSUE TITLE
About lmlsb extract

### ISSUE THREAD

**Issue by MKleines** [pmrowla/pylivemaker#18]
* pylivemaker version:0.1.2
* Python version:3.7
* Operating System:win10

Hello,I tried to use the lmlsb extract command to extract lsb but there comes an error.
I have no idea of how to deal with it. Here's the trace back.

> F:\livemakertrans\output1>lmlsb extract 00000757.lsb -o 00000757
Extracting scripts from 00000757.lsb
  wrote 00000757\00000757-0000075A.lns
  wrote 00000757\00000757-0000075C.lns
ValueError: 5 is not a valid VAlignEnum

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ppl\AppData\Local\Programs\Python\Python37\Scripts\lmlsb.exe\__main__.py", line 9, in <module>
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\livemaker\cli.py", line 356, in extract
    f.write(dec.decompile(scenario))
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\livemaker\lsb\novel.py", line 1133, in decompile
    return self._decompile_full(tpword)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\livemaker\lsb\novel.py", line 1090, in _decompile_full
    self._line.append(str(w))
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\livemaker\lsb\novel.py", line 538, in __str__
    'ALIGN': VAlignEnum(self.align).name,
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\enum.py", line 564, in __new__
    raise exc
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "c:\users\ppl\appdata\local\programs\python\python37\lib\enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 5 is not a valid VAlignEnum

**Comment by pmrowla** [comment]
It looks like your LSB file contains some scripts that are unsupported by pylivemaker

basically, the vertical text alignment field only has 3 documented possible values, but for some reason some files use other values which is why there is already an edge case for `4` in

https://github.com/pmrowla/pylivemaker/blob/0bf308c5adff5ef57e8612e1850df6009d4c41d9/livemaker/lsb/novel.py#L81-L87

but for your file, there's another undocumented value being used (`5`). If you attach your `00000757.lsb` file to this issue so I can investigate this it would be appreciated

In the meantime, if you manually add a new case:

```
    UNKNOWN2 = 5
```

 to the end of the that VAlign enum at line 88 in `c:\users\ppl\appdata\local\programs\python\python37\lib\site-packages\livemaker\lsb\novel.py` I think you should at least be able to extract the scripts.

**Comment by MKleines** [comment]
Thank you for your kind reply :)
Here's `00000757.lsb`,since Github does not support `.lsb`  file,it is renamed to `00000757.lsb.txt`
[00000757.lsb.txt](https://github.com/pmrowla/pylivemaker/files/4207690/00000757.lsb.txt)

**Comment by pmrowla** [comment]
This issue is fixed in the latest release (0.2.0)
