### ISSUE TITLE
error when extract lsb file

### ISSUE THREAD

**Issue by keng1308** [pmrowla/pylivemaker#22]
* pylivemaker version:0.2.0
* Python version:3.7.7
* Operating System:win 10
* LiveMaker game:
Try to extract lsb file but got some error may be i miss something?

 D:\livemaker\game_files> lmlsb extract 00000011.lsb -o 00000011
Extracting scripts from 00000011.lsb
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\lmlsb.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\livemaker\cli.py", line 356, in extract
    with open(output_dir.joinpath(lsb_ref_filename), 'w', encoding=encoding) as lsb_ref_file:
FileNotFoundError: [Errno 2] No such file or directory: '00000011\\00000011.lsbref'

**Comment by pmrowla** [comment]
There is a bug in `lmlsb extract` where it doesn't create the output folder properly. I'll push a fix for it soon, but in the meantime you can get around it by just creating the `00000011` folder yourself before running the extract command.
