### ISSUE TITLE
Module Not Found Error : livemaker.lsb

### ISSUE THREAD

**Issue by jenga12** [pmrowla/pylivemaker#4]
Hi, May I ask you a question about pylivemaker?

### My PC Environment
pylivemaker : 0.1.0
Python : ver3.7.3
OS : Windows10 Home Premium (Japanese)
Livemaker game : RJ065120 (DLsite Product ID)
Memory : 8GB

and Installed Livemaker3

### Description
I want to convert .lsb to txt file.

First, I installed python 3.7.3 and pylivemaker by pip.
Next, I tried to print pylivemaker usage on command line.
ex, "lmar --help", "lmlsb --help".
but get this error,
"Module Not Found Error : No module named 'livemaker.lsb'".

This error is getted other command.
ex, "lmlsb dump ゲームメイン.lsb > gamemain.txt"

It's a bug ?
Or I forgot to do something?

### install -> run command log
Microsoft Windows [Version 10.0.17134.706]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\MY_USER_NAME>pip install pylivemaker
Collecting pylivemaker
  Using cached https://files.pythonhosted.org/packages/c2/5a/4b3a87c7b28ae2d0774ad21a4f859a7751434a92ddac7b67cca14aa7c0e6/pylivemaker-0.1.0-py2.py3-none-any.whl
Requirement already satisfied: Pillow>=5.4.1 in c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages (from pylivemaker) (6.0.0)
Requirement already satisfied: lxml>=4.3 in c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages (from pylivemaker) (4.3.3)
Requirement already satisfied: numpy>=1.16 in c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages (from pylivemaker) (1.16.2)
Requirement already satisfied: Click>=6.0 in c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages (from pylivemaker) (7.0)
Requirement already satisfied: construct>=2.9 in c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages (from pylivemaker) (2.9.45)
Installing collected packages: pylivemaker
Successfully installed pylivemaker-0.1.0

C:\Users\MY_USER_NAME>lmar --help
Traceback (most recent call last):
  File "c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MY_USER_NAME\AppData\Local\Programs\Python\Python37\Scripts\lmar.exe\__main__.py", line 5, in <module>
  File "c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages\livemaker\__init__.py", line 28, in <module>
    from .lsb import LMScript, LNSCompiler, LNSDecompiler
ModuleNotFoundError: No module named 'livemaker.lsb'

C:\Users\MY_USER_NAME>lmlsb --help
Traceback (most recent call last):
  File "c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MY_USER_NAME\AppData\Local\Programs\Python\Python37\Scripts\lmlsb.exe\__main__.py", line 5, in <module>
  File "c:\users\MY_USER_NAME\appdata\local\programs\python\python37\lib\site-packages\livemaker\__init__.py", line 28, in <module>
    from .lsb import LMScript, LNSCompiler, LNSDecompiler
ModuleNotFoundError: No module named 'livemaker.lsb'

**Comment by pmrowla** [comment]
It looks like there is an problem with how the package is installed in windows through pip, I'll look into this issue.

**Comment by pmrowla** [comment]
This should be resolved once the next travis build finishes and the package update gets pushed to pypi (it might take a couple of hours from now for travis to actually do the build though).

After that point, you should be able to just do
```
pip install --upgrade pylivemaker
```
and then try running `lmar` or `lmlsb` like before. If it still isn't working after the update, just reopen this issue.
