### ISSUE TITLE
text insert API doesn't work for out of order LSB files

### ISSUE THREAD

**Issue by pmrowla** [pmrowla/pylivemaker#48]
via @LioMajor
> > After this update, inserting doesn't work well anymore.
> 
> ```
> Patching 000000A4.lsb ...
> Traceback (most recent call last):
> File "C:\python\Scripts\lmlsb-script.py", line 11, in
> load_entry_point('pylivemaker==1.0.0.dev0', 'console_scripts', 'lmlsb')()
> File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in **call**
> return self.main(*args, **kwargs)
> File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
> rv = self.invoke(ctx)
> File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
> return callback(*args, **kwargs)
> File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\cli\lmlsb.py", line 1288, in insertcsv
> translated, untranslated = _patch_csv_text(lsb, lsb_file, csv_data, verbose)
> File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\cli\lmlsb.py", line 1247, in _patch_csv_text
> lsb.replace_text(text_objects)
> File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\lsb\lmscript.py", line 531, in replace_text
> self.replace_text_blocks(new_objs["text"])
> File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\lsb\lmscript.py", line 548, in replace_text_blocks
> raise BadTextIdentifierError(f"invalid text block: LSB command '{line_no}' is not TextIns")
> livemaker.exceptions.BadTextIdentifierError: invalid text block: LSB command '260' is not TextIns
> ```
> 
> I reverted back before this changes, and it works.

**Comment by pmrowla** [comment]
file has command line numbers that don't align with actual command index
ex:
```
...
 515: Call 00000CA4.lsb:6  1 
 516: Jump 000000A4.lsb:911 1
 517: Wait 1 0 0
 518: Label 00002E27
 520: Call 00000CA4.lsb:440  1 
 522: ObjDel "男"
 523: ObjDel "ギャラリー"
 525: Calc 顔番号 = 0
...
```
519, 521, etc do not exist in the lsb, they were probably comment commands that get removed on lsb compilation

basically we need a way to refer directly to commands by line_no instead of raw index

**Comment by pmrowla** [comment]
@LioMajor thanks for sending the lsb, this should be fixed for you in latest master
