### ISSUE TITLE
extractmenu doesn't use UTF-8

### ISSUE THREAD

**Issue by LioMajor** [pmrowla/pylivemaker#50]
* pylivemaker version: 09-05-2020
* Python version: 3.7
* Operating System: Win 10

extractmenu can't export and import menu parts that still has japanese chars inside

C:\test>lmlsb extractmenu 000000A4.lsb 000000A4.csv
Extracting 000000A4.lsb ...
Traceback (most recent call last):
  File "C:\python\Scripts\lmlsb-script.py", line 11, in <module>
    load_entry_point('pylivemaker==1.0.0.dev0', 'console_scripts', 'lmlsb')()
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\cli\lmlsb.py", line 947, in extractmenu
    csv_writer.writerow(row)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-23: character maps to <undefined>

**Comment by pmrowla** [comment]
This will be fixed when the menu stuff goes into the core api
