### ISSUE TITLE
logger needs to be set to use utf-8

### ISSUE THREAD

**Issue by pmrowla** [pmrowla/pylivemaker#56]
see: https://github.com/pmrowla/pylivemaker/commit/a2f615acbe0269867b052f02937eb2e20babc0f7#commitcomment-39063204

**Comment by LioMajor** [comment]
The problem is not fixed, it still shows like this:

```
  [################--------------------]   45%  00:00:03  グラフィック\system\skill_06_off.gal   --- Logging error in Loguru Handler #2 ---
Record was: {'elapsed': datetime.timedelta(seconds=2, microseconds=488463), 'exception': None, 'extra': {}, 'file': (name='lmpatch.py', path='c:\\python\\lib\\site-packages\\pylivemaker-1.0.0.dev0-py3.7.egg\\livemaker\\cli\\lmpatch.py'), 'function': 'lmpatch', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 154, 'message': 'copied グラフィック\\system\\skill_06_pv.gal', 'module': 'lmpatch', 'name': 'livemaker.cli.lmpatch', 'process': (id=2552, name='MainProcess'), 'thread': (id=7248, name='MainThread'), 'time': datetime(2020, 5, 11, 1, 5, 46, 837743, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200), 'Central European Summer Time'))}
Traceback (most recent call last):
  File "c:\python\lib\site-packages\loguru-0.4.1-py3.7.egg\loguru\_handler.py", line 177, in emit
    self._sink.write(str_record)
  File "c:\python\lib\site-packages\loguru-0.4.1-py3.7.egg\loguru\_file_sink.py", line 179, in write
    self._file.write(message)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 80-85: character maps to <undefined>
--- End of logging error ---
```

**Comment by pmrowla** [comment]
Probably something windows only, I’ll look into it some more

**Comment by pmrowla** [comment]
@LioMajor can you try latest master and see if it fixes this issue for you in windows

**Comment by LioMajor** [comment]
```
lmpatch -r game.exe insert
Generating new archive contents...
  [####################################]  100%                                                                     
Writing new archive files...
Cleaning up temporary files...
```
It works now again like it should, thx :)
