### ISSUE TITLE
I met something about AttributeError

### ISSUE THREAD

**Issue by pet345** [pmrowla/pylivemaker#70]
* pylivemaker version:1.0.0
* Python version:3.6.8
* Operating System:Windows 10
* LiveMaker game:

### Description

I want to run this line of instructions
lmlsb dump ゲームメイン.lsb -o gamemain.txt
&
lmgraph ゲームメイン.lsb
But the following error appears
It’s still available at 0.3.2

### What I Did

```
Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\peter\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\Scripts\lmlsb.exe\__main__.py", line 4, in <module>
  File "c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\livemaker\cli\__init__.py", line 40, in <module>
    sys.stdout.reconfigure(encoding="utf-8", errors="backslashreplace")
AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'
```
Sorry
Because my mother tongue is Chinese, I use google translation

**Comment by pmrowla** [comment]
This is a bug specific to Python 3.6 on Windows.

For now, you can work around it by using Python 3.7 or above.

**Comment by pmrowla** [comment]
Closing this since master no longer supports py <3.8 (and 3.6 is completely EOL now)
