### ISSUE TITLE
The term 'lmar' is not recognized.

### ISSUE THREAD

**Issue by SirDerpTheDerp** [pmrowla/pylivemaker#87]
* pylivemaker version: 1.1.0
* Python version: 3.11.0
* Operating System: Windows 10
* LiveMaker game: --

### Description

While attempting to use the lmar command, it tells me the term 'lmar' is not recognized.

### What I Did

```
 C:\Windows\system32> lmar x game.exe -o game_files
lmar : The term 'lmar' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ lmar x game.exe -o game_files
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (lmar:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by ship-j** [comment]
Not an issue, adding python to your path (environmental variables) would fix this.

**Comment by SirDerpTheDerp** [comment]
That seemed to fix the issue. Thank you. But I've recently come across a new issue when trying to patch my lsb to the .exe, which tells me: "IndexError: list index out of range"

C:\Windows\system32\game_files> lmpatch game.exe 00000001.lsb
Generating new archive contents...
2022-12-23 22:42:34.294 | ERROR    | livemaker.cli.lmpatch:lmpatch:171 - list index out of range
Cleaning up temporary files...
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 126, in lmpatch
    with click.progressbar(orig_lm.infolist(), item_show_func=bar_show) as bar:
  File "C:\Python311\Lib\site-packages\click\_termui_impl.py", line 98, in __enter__
    self.render_progress()
  File "C:\Python311\Lib\site-packages\click\_termui_impl.py", line 242, in render_progress
    line = self.format_progress_line()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\_termui_impl.py", line 199, in format_progress_line
    item_info = self.item_show_func(self.current_item)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 118, in bar_show
    width, _ = click.get_terminal_size()
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'click' has no attribute 'get_terminal_size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\lmpatch.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 173, in lmpatch
    raise e
  File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 113, in lmpatch
    with LMArchive(
  File "C:\Python311\Lib\site-packages\livemaker\archive.py", line 702, in __exit__
    self.close()
  File "C:\Python311\Lib\site-packages\livemaker\archive.py", line 720, in close
    self._write_directory()
  File "C:\Python311\Lib\site-packages\livemaker\archive.py", line 1104, in _write_directory
    last_entry = self.filelist[-1]
                 ~~~~~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by ship-j** [comment]
Yeah, I had this too. Which is strange — #85 discusses the click issue and it was fixed months ago, yet on mine (installed when I responded to you) it still has the older code. Replace “click” with “shutil” on line 118 of lmpatch.On Dec 24, 2022, at 12:53 AM, SirDerpTheDerp ***@***.***> wrote:﻿
That seemed to fix the issue. Thank you. But I've recently come across a new issue when trying to patch my lsb to the .exe, which tells me: "IndexError: list index out of range"
C:\Windows\system32\game_files> lmpatch game.exe 00000001.lsb
Generating new archive contents...
2022-12-23 22:42:34.294 | ERROR    | livemaker.cli.lmpatch:lmpatch:171 - list index out of range
Cleaning up temporary files...
Traceback (most recent call last):
File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 126, in lmpatch
with click.progressbar(orig_lm.infolist(), item_show_func=bar_show) as bar:
File "C:\Python311\Lib\site-packages\click_termui_impl.py", line 98, in enter
self.render_progress()
File "C:\Python311\Lib\site-packages\click_termui_impl.py", line 242, in render_progress
line = self.format_progress_line()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\click_termui_impl.py", line 199, in format_progress_line
item_info = self.item_show_func(self.current_item)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 118, in bar_show
width, _ = click.get_terminal_size()
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'click' has no attribute 'get_terminal_size'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\Python311\Scripts\lmpatch.exe_main.py", line 7, in 
File "C:\Python311\Lib\site-packages\click\core.py", line 1130, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\click\core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\click\core.py", line 760, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 173, in lmpatch
raise e
File "C:\Python311\Lib\site-packages\livemaker\cli\lmpatch.py", line 113, in lmpatch
with LMArchive(
File "C:\Python311\Lib\site-packages\livemaker\archive.py", line 702, in exit
self.close()
File "C:\Python311\Lib\site-packages\livemaker\archive.py", line 720, in close
self._write_directory()
File "C:\Python311\Lib\site-packages\livemaker\archive.py", line 1104, in _write_directory
last_entry = self.filelist[-1]
~~~~~~~~~~~~~^^^^
IndexError: list index out of range

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by pmrowla** [comment]
I must have forgotten to do a release after merging the fix, will push a new release later today

**Comment by pmrowla** [comment]
Should be resolved in 1.0.3

**Comment by ship-j** [comment]
You’re goated.  This is a phenomenal project and it’s cool that you still support it.

**Comment by SirDerpTheDerp** [comment]
Nice. Thank you for all the help.
